chore: Fixed up backup agent error handling.

diff --git a/packages/docker/backup-agent/backup-agent/scripts/rclone_exec b/packages/docker/backup-agent/backup-agent/scripts/rclone_exec
--- a/packages/docker/backup-agent/backup-agent/scripts/rclone_exec
+++ b/packages/docker/backup-agent/backup-agent/scripts/rclone_exec
@@ -44,4 +44,7 @@ if [[ -n "${RCLONE_URL}" ]]; then
   args+=( "${RCLONE_URL}" )
 fi
 
-rclone rc "${1}" "${args[@]}" "${@:2}"
+if ! rclone rc "${1}" "${args[@]}" "${@:2}" ; then
+  >&2 echo "Failed to execute rclone command: ${1}"
+  exit 1
+fi
